workspace:
  base: /go/src
  path: github.com/appleboy/drone-ssh

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  lint:
    image: golang:1.11
    pull: true
    environment:
      - GO111MODULE=on
    group: golang
    commands:
      - make vet
      - make lint

  linux_amd64:
    image: golang:1.11
    pull: true
    group: golang
    environment:
      - GO111MODULE=on
    commands:
      - make linux_amd64

  linux_arm64:
    image: golang:1.11
    pull: true
    group: golang
    environment:
      - GO111MODULE=on
    commands:
      - make linux_arm64

  linux_arm:
    image: golang:1.11
    pull: true
    group: golang
    environment:
      - GO111MODULE=on
    commands:
      - make linux_arm

  test:
    image: golang:1.11
    pull: true
    group: golang
    environment:
      - GO111MODULE=on
    commands:
      - make ssh-server
      - make test
      - make coverage

  release:
    image: golang:1.11
    pull: true
    environment:
      - GO111MODULE=on
    commands:
      - make release
    when:
      event: [ tag ]
      local: false

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - .cover/coverage.txt
    when:
      event: [ push, pull_request ]
      status: [ success ]

  publish:
    image: plugins/docker
    pull: true
    repo: ${DRONE_REPO}
    default_tags: true
    secrets: [ docker_username, docker_password ]
    group: release
    when:
      event: [ push, tag ]
      local: false

  release_tag:
    image: plugins/github-release
    pull: true
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      local: false

  microbadger:
    image: plugins/webhook:1
    pull: true
    secrets: [ webhook_url ]
    when:
      status: [ success ]

  discord:
    image: appleboy/drone-discord
    pull: true
    secrets: [ discord_webhook_id, discord_webhook_token ]
    when:
      status: [ changed, failure ]
