workspace:
  base: /go/src
  path: github.com/appleboy/drone-ssh

clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

pipeline:
  lint:
    image: appleboy/golang-testing
    pull: true
    group: golang
    commands:
      - make vet
      - make lint
      - make test-vendor

  linux_amd64:
    image: appleboy/golang-testing
    pull: true
    group: golang
    commands:
      - make linux_amd64

  linux_arm64:
    image: appleboy/golang-testing
    pull: true
    group: golang
    commands:
      - make linux_arm64

  linux_arm:
    image: appleboy/golang-testing
    pull: true
    group: golang
    commands:
      - make linux_arm

  test:
    image: appleboy/golang-testing
    pull: true
    group: golang
    commands:
      - make ssh-server
      - make test
      - make coverage

  release:
    image: appleboy/golang-testing
    pull: true
    commands:
      - make release
    when:
      event: [ tag ]
      local: false

  codecov:
    image: robertstettner/drone-codecov
    secrets: [ codecov_token ]
    files:
      - .cover/coverage.txt
    when:
      event: [ push, pull_request ]
      status: [ success ]

  publish:
    image: plugins/docker
    pull: true
    repo: ${DRONE_REPO}
    default_tags: true
    secrets: [ docker_username, docker_password ]
    group: release
    when:
      event: [ push, tag ]
      local: false

  release_tag:
    image: plugins/github-release
    pull: true
    secrets: [ github_release_api_key ]
    group: release
    files:
      - dist/release/*
    when:
      event: [ tag ]
      local: false

  facebook:
    image: appleboy/drone-facebook
    secrets: [ fb_page_token, fb_verify_token ]
    pull: true
    to: 1234973386524610
    when:
      status: [ changed, failure ]
